"""Compress the embedded dashboard before C++ compilation.

web_assets.h remains the readable/editable source. This pre-build step emits a
small byte array so the full dashboard costs roughly one quarter as much flash.
The gzip timestamp is fixed, keeping firmware builds reproducible.
"""

from pathlib import Path
import gzip
import re

Import("env")  # type: ignore[name-defined]  # supplied by PlatformIO/SCons

project = Path(env.subst("$PROJECT_DIR"))  # type: ignore[name-defined]
source_path = project / "src" / "web_assets.h"
output_path = project / "src" / "web_assets_gzip.h"
source = source_path.read_text(encoding="utf-8")

icon_match = re.search(r'R"ICON\((.*?)\)ICON";', source, re.DOTALL)
html_match = re.search(r'R"DASH\((.*?)\)DASH";', source, re.DOTALL)
if not icon_match or not html_match:
    raise RuntimeError("Could not find dashboard raw-string markers")

payload = gzip.compress(html_match.group(1).encode("utf-8"), compresslevel=9, mtime=0)
rows = []
for offset in range(0, len(payload), 16):
    rows.append("  " + ", ".join(f"0x{byte:02x}" for byte in payload[offset:offset + 16]))

generated = """// Generated by scripts/embed_web.py; edit web_assets.h instead.\n#pragma once\n#include <Arduino.h>\n\n"""
generated += 'static const char DASHBOARD_ICON[] PROGMEM = R"ICON(' + icon_match.group(1) + ')ICON";\n\n'
generated += "static const uint8_t DASHBOARD_GZIP[] PROGMEM = {\n"
generated += ",\n".join(rows)
generated += "\n};\nstatic const size_t DASHBOARD_GZIP_LEN = sizeof(DASHBOARD_GZIP);\n"

if not output_path.exists() or output_path.read_text(encoding="utf-8") != generated:
    output_path.write_text(generated, encoding="utf-8", newline="\n")
