#include "text_arabic.h"

#include <string.h>

namespace {

/// Joining classes, in the sense ArabicShaping.txt uses them.
///
/// The names describe which side of a letter accepts a connection, and the one
/// that reads backwards is JOIN_RIGHT: a right-joining letter connects on its
/// right-hand side, and in a right-to-left script that is the side facing the
/// *preceding* letter. So JOIN_RIGHT letters -- alef, dal, reh, waw and the
/// rest -- join backwards only, which is why a word breaks after them.
enum : uint8_t {
  JOIN_NONE = 0,     ///< joins nothing: hamza, digits, punctuation
  JOIN_RIGHT,        ///< joins backwards only; isolated and final shapes only
  JOIN_DUAL,         ///< joins both ways; all four shapes
  JOIN_CAUSING,      ///< tatweel and ZWJ: joins both ways, has no shape itself
  JOIN_TRANSPARENT,  ///< a mark; invisible to its neighbours' shaping
};

enum : uint8_t { FORM_ISOLATED = 0, FORM_FINAL, FORM_INITIAL, FORM_MEDIAL };

struct ArabicForms {
  uint16_t base;
  uint16_t form[4];  ///< indexed by FORM_*; 0 where the shape does not exist
};

// GENERATED by scripts/gen_arabic_tables.py -- do not edit by hand.
// Run that script to check this still matches Unicode.

/// Joining class of every codepoint in the Arabic block, indexed
/// by (cp - 0x0600). See gen_arabic_tables.py for the source data.
static const uint8_t JOINING_CLASS[256] = {
    JOIN_NONE       , JOIN_NONE       , JOIN_NONE       , JOIN_NONE       , JOIN_NONE       , JOIN_NONE       , JOIN_NONE       , JOIN_NONE,  // U+0600
    JOIN_NONE       , JOIN_NONE       , JOIN_NONE       , JOIN_NONE       , JOIN_NONE       , JOIN_NONE       , JOIN_NONE       , JOIN_NONE,  // U+0608
    JOIN_TRANSPARENT, JOIN_TRANSPARENT, JOIN_TRANSPARENT, JOIN_TRANSPARENT, JOIN_TRANSPARENT, JOIN_TRANSPARENT, JOIN_TRANSPARENT, JOIN_TRANSPARENT,  // U+0610
    JOIN_TRANSPARENT, JOIN_TRANSPARENT, JOIN_TRANSPARENT, JOIN_NONE       , JOIN_NONE       , JOIN_NONE       , JOIN_NONE       , JOIN_NONE,  // U+0618
    JOIN_DUAL       , JOIN_NONE       , JOIN_RIGHT      , JOIN_RIGHT      , JOIN_RIGHT      , JOIN_RIGHT      , JOIN_DUAL       , JOIN_RIGHT,  // U+0620
    JOIN_DUAL       , JOIN_RIGHT      , JOIN_DUAL       , JOIN_DUAL       , JOIN_DUAL       , JOIN_DUAL       , JOIN_DUAL       , JOIN_RIGHT,  // U+0628
    JOIN_RIGHT      , JOIN_RIGHT      , JOIN_RIGHT      , JOIN_DUAL       , JOIN_DUAL       , JOIN_DUAL       , JOIN_DUAL       , JOIN_DUAL,  // U+0630
    JOIN_DUAL       , JOIN_DUAL       , JOIN_DUAL       , JOIN_DUAL       , JOIN_DUAL       , JOIN_DUAL       , JOIN_DUAL       , JOIN_DUAL,  // U+0638
    JOIN_CAUSING    , JOIN_DUAL       , JOIN_DUAL       , JOIN_DUAL       , JOIN_DUAL       , JOIN_DUAL       , JOIN_DUAL       , JOIN_DUAL,  // U+0640
    JOIN_RIGHT      , JOIN_RIGHT      , JOIN_DUAL       , JOIN_TRANSPARENT, JOIN_TRANSPARENT, JOIN_TRANSPARENT, JOIN_TRANSPARENT, JOIN_TRANSPARENT,  // U+0648
    JOIN_TRANSPARENT, JOIN_TRANSPARENT, JOIN_TRANSPARENT, JOIN_TRANSPARENT, JOIN_TRANSPARENT, JOIN_TRANSPARENT, JOIN_TRANSPARENT, JOIN_TRANSPARENT,  // U+0650
    JOIN_TRANSPARENT, JOIN_TRANSPARENT, JOIN_TRANSPARENT, JOIN_TRANSPARENT, JOIN_TRANSPARENT, JOIN_TRANSPARENT, JOIN_TRANSPARENT, JOIN_TRANSPARENT,  // U+0658
    JOIN_NONE       , JOIN_NONE       , JOIN_NONE       , JOIN_NONE       , JOIN_NONE       , JOIN_NONE       , JOIN_NONE       , JOIN_NONE,  // U+0660
    JOIN_NONE       , JOIN_NONE       , JOIN_NONE       , JOIN_NONE       , JOIN_NONE       , JOIN_NONE       , JOIN_DUAL       , JOIN_RIGHT,  // U+0668
    JOIN_TRANSPARENT, JOIN_RIGHT      , JOIN_RIGHT      , JOIN_RIGHT      , JOIN_NONE       , JOIN_NONE       , JOIN_RIGHT      , JOIN_RIGHT,  // U+0670
    JOIN_DUAL       , JOIN_DUAL       , JOIN_DUAL       , JOIN_DUAL       , JOIN_DUAL       , JOIN_DUAL       , JOIN_DUAL       , JOIN_DUAL,  // U+0678
    JOIN_DUAL       , JOIN_DUAL       , JOIN_DUAL       , JOIN_DUAL       , JOIN_DUAL       , JOIN_DUAL       , JOIN_DUAL       , JOIN_DUAL,  // U+0680
    JOIN_RIGHT      , JOIN_RIGHT      , JOIN_RIGHT      , JOIN_RIGHT      , JOIN_RIGHT      , JOIN_RIGHT      , JOIN_RIGHT      , JOIN_RIGHT,  // U+0688
    JOIN_RIGHT      , JOIN_RIGHT      , JOIN_RIGHT      , JOIN_RIGHT      , JOIN_RIGHT      , JOIN_RIGHT      , JOIN_RIGHT      , JOIN_RIGHT,  // U+0690
    JOIN_RIGHT      , JOIN_RIGHT      , JOIN_DUAL       , JOIN_DUAL       , JOIN_DUAL       , JOIN_DUAL       , JOIN_DUAL       , JOIN_DUAL,  // U+0698
    JOIN_DUAL       , JOIN_DUAL       , JOIN_DUAL       , JOIN_DUAL       , JOIN_DUAL       , JOIN_DUAL       , JOIN_DUAL       , JOIN_DUAL,  // U+06A0
    JOIN_DUAL       , JOIN_DUAL       , JOIN_DUAL       , JOIN_DUAL       , JOIN_DUAL       , JOIN_DUAL       , JOIN_DUAL       , JOIN_DUAL,  // U+06A8
    JOIN_DUAL       , JOIN_DUAL       , JOIN_DUAL       , JOIN_DUAL       , JOIN_DUAL       , JOIN_DUAL       , JOIN_DUAL       , JOIN_DUAL,  // U+06B0
    JOIN_DUAL       , JOIN_DUAL       , JOIN_DUAL       , JOIN_DUAL       , JOIN_DUAL       , JOIN_DUAL       , JOIN_DUAL       , JOIN_DUAL,  // U+06B8
    JOIN_RIGHT      , JOIN_DUAL       , JOIN_DUAL       , JOIN_RIGHT      , JOIN_RIGHT      , JOIN_RIGHT      , JOIN_RIGHT      , JOIN_RIGHT,  // U+06C0
    JOIN_RIGHT      , JOIN_RIGHT      , JOIN_RIGHT      , JOIN_RIGHT      , JOIN_DUAL       , JOIN_RIGHT      , JOIN_DUAL       , JOIN_RIGHT,  // U+06C8
    JOIN_DUAL       , JOIN_DUAL       , JOIN_RIGHT      , JOIN_RIGHT      , JOIN_NONE       , JOIN_RIGHT      , JOIN_TRANSPARENT, JOIN_TRANSPARENT,  // U+06D0
    JOIN_TRANSPARENT, JOIN_TRANSPARENT, JOIN_TRANSPARENT, JOIN_TRANSPARENT, JOIN_TRANSPARENT, JOIN_NONE       , JOIN_NONE       , JOIN_TRANSPARENT,  // U+06D8
    JOIN_TRANSPARENT, JOIN_TRANSPARENT, JOIN_TRANSPARENT, JOIN_TRANSPARENT, JOIN_TRANSPARENT, JOIN_NONE       , JOIN_NONE       , JOIN_TRANSPARENT,  // U+06E0
    JOIN_TRANSPARENT, JOIN_NONE       , JOIN_TRANSPARENT, JOIN_TRANSPARENT, JOIN_TRANSPARENT, JOIN_TRANSPARENT, JOIN_RIGHT      , JOIN_RIGHT,  // U+06E8
    JOIN_NONE       , JOIN_NONE       , JOIN_NONE       , JOIN_NONE       , JOIN_NONE       , JOIN_NONE       , JOIN_NONE       , JOIN_NONE,  // U+06F0
    JOIN_NONE       , JOIN_NONE       , JOIN_DUAL       , JOIN_DUAL       , JOIN_DUAL       , JOIN_NONE       , JOIN_NONE       , JOIN_DUAL,  // U+06F8
};

/// base letter -> {isolated, final, initial, medial}; 0 where the
/// letter has no such shape. Sorted, so lookup can bisect.
static const ArabicForms FORMS[] = {
    {0x0621, {0xFE80, 0x0000, 0x0000, 0x0000}},
    {0x0622, {0xFE81, 0xFE82, 0x0000, 0x0000}},
    {0x0623, {0xFE83, 0xFE84, 0x0000, 0x0000}},
    {0x0624, {0xFE85, 0xFE86, 0x0000, 0x0000}},
    {0x0625, {0xFE87, 0xFE88, 0x0000, 0x0000}},
    {0x0626, {0xFE89, 0xFE8A, 0xFE8B, 0xFE8C}},
    {0x0627, {0xFE8D, 0xFE8E, 0x0000, 0x0000}},
    {0x0628, {0xFE8F, 0xFE90, 0xFE91, 0xFE92}},
    {0x0629, {0xFE93, 0xFE94, 0x0000, 0x0000}},
    {0x062A, {0xFE95, 0xFE96, 0xFE97, 0xFE98}},
    {0x062B, {0xFE99, 0xFE9A, 0xFE9B, 0xFE9C}},
    {0x062C, {0xFE9D, 0xFE9E, 0xFE9F, 0xFEA0}},
    {0x062D, {0xFEA1, 0xFEA2, 0xFEA3, 0xFEA4}},
    {0x062E, {0xFEA5, 0xFEA6, 0xFEA7, 0xFEA8}},
    {0x062F, {0xFEA9, 0xFEAA, 0x0000, 0x0000}},
    {0x0630, {0xFEAB, 0xFEAC, 0x0000, 0x0000}},
    {0x0631, {0xFEAD, 0xFEAE, 0x0000, 0x0000}},
    {0x0632, {0xFEAF, 0xFEB0, 0x0000, 0x0000}},
    {0x0633, {0xFEB1, 0xFEB2, 0xFEB3, 0xFEB4}},
    {0x0634, {0xFEB5, 0xFEB6, 0xFEB7, 0xFEB8}},
    {0x0635, {0xFEB9, 0xFEBA, 0xFEBB, 0xFEBC}},
    {0x0636, {0xFEBD, 0xFEBE, 0xFEBF, 0xFEC0}},
    {0x0637, {0xFEC1, 0xFEC2, 0xFEC3, 0xFEC4}},
    {0x0638, {0xFEC5, 0xFEC6, 0xFEC7, 0xFEC8}},
    {0x0639, {0xFEC9, 0xFECA, 0xFECB, 0xFECC}},
    {0x063A, {0xFECD, 0xFECE, 0xFECF, 0xFED0}},
    {0x0641, {0xFED1, 0xFED2, 0xFED3, 0xFED4}},
    {0x0642, {0xFED5, 0xFED6, 0xFED7, 0xFED8}},
    {0x0643, {0xFED9, 0xFEDA, 0xFEDB, 0xFEDC}},
    {0x0644, {0xFEDD, 0xFEDE, 0xFEDF, 0xFEE0}},
    {0x0645, {0xFEE1, 0xFEE2, 0xFEE3, 0xFEE4}},
    {0x0646, {0xFEE5, 0xFEE6, 0xFEE7, 0xFEE8}},
    {0x0647, {0xFEE9, 0xFEEA, 0xFEEB, 0xFEEC}},
    {0x0648, {0xFEED, 0xFEEE, 0x0000, 0x0000}},
    {0x0649, {0xFEEF, 0xFEF0, 0x0000, 0x0000}},
    {0x064A, {0xFEF1, 0xFEF2, 0xFEF3, 0xFEF4}},
    {0x067E, {0xFB56, 0xFB57, 0xFB58, 0xFB59}},
    {0x0686, {0xFB7A, 0xFB7B, 0xFB7C, 0xFB7D}},
    {0x0698, {0xFB8A, 0xFB8B, 0x0000, 0x0000}},
    {0x06A9, {0xFB8E, 0xFB8F, 0xFB90, 0xFB91}},
    {0x06AF, {0xFB92, 0xFB93, 0xFB94, 0xFB95}},
    {0x06CC, {0xFEEF, 0xFEF0, 0xFEF3, 0xFEF4}},
};

/// lam + alef, which must always combine: {alef, isolated, final}.
static const uint16_t LAM_ALEF[][3] = {
    {0x0622, 0xFEF5, 0xFEF6},
    {0x0623, 0xFEF7, 0xFEF8},
    {0x0625, 0xFEF9, 0xFEFA},
    {0x0627, 0xFEFB, 0xFEFC},
};
// ------------------------------- end generated -------------------------------

/*
 * Farsi yeh, and the one substitution in the table above.
 *
 * U+06CC maps to U+FEEF/FEF0/FEF3/FEF4 -- shapes that belong to alef maksura
 * and Arabic yeh -- rather than to its own U+FBFC..FBFF. That is not a
 * shortcut: none of the three Arabic fonts u8g2 ships carries U+FBFC..FBFF,
 * which was established by parsing u8g2_fonts.c rather than assumed, so mapping
 * it honestly would leave the commonest letter in Persian permanently
 * unjoined. The borrowed shapes are the right ones anyway -- alef maksura is a
 * dotless yeh, which is exactly the Persian isolated and final form, and the
 * initial and medial Arabic yeh shapes carry no dots either.
 */

constexpr size_t MAX_CP = 96;  ///< codepoints handled in one string

/// Bidirectional class, reduced to what a single line of mixed text needs.
enum : uint8_t { DIR_LTR = 0, DIR_RTL, DIR_NEUTRAL };

inline bool is_arabic_block(uint32_t cp) { return cp >= 0x0600 && cp <= 0x06FF; }

uint8_t joining_class(uint32_t cp) {
  if (is_arabic_block(cp)) return JOINING_CLASS[cp - 0x0600];
  // U+200D ZERO WIDTH JOINER forces a join, U+200C NON-JOINER forbids one.
  // Neither has a glyph; both are dropped after they have done their work.
  if (cp == 0x200D) return JOIN_CAUSING;
  return JOIN_NONE;
}

const ArabicForms *find_forms(uint32_t cp) {
  size_t lo = 0, hi = sizeof(FORMS) / sizeof(FORMS[0]);
  while (lo < hi) {
    const size_t mid = (lo + hi) / 2;
    if (FORMS[mid].base == cp) return &FORMS[mid];
    if (FORMS[mid].base < cp) lo = mid + 1;
    else hi = mid;
  }
  return nullptr;
}

uint8_t bidi_class(uint32_t cp) {
  // Arabic letters, marks and punctuation all run right to left...
  if (is_arabic_block(cp) || (cp >= 0xFB50 && cp <= 0xFDFF) ||
      (cp >= 0xFE70 && cp <= 0xFEFF)) {
    // ...except the digits, which read left to right even inside Persian text,
    // the same way 2024 does in an English sentence.
    if (cp >= 0x0660 && cp <= 0x0669) return DIR_LTR;  // Arabic-Indic
    if (cp >= 0x06F0 && cp <= 0x06F9) return DIR_LTR;  // Persian
    return DIR_RTL;
  }
  if ((cp >= 'a' && cp <= 'z') || (cp >= 'A' && cp <= 'Z')) return DIR_LTR;
  if (cp >= '0' && cp <= '9') return DIR_LTR;
  if (cp >= 0x00C0 && cp <= 0x024F) return DIR_LTR;  // accented Latin
  return DIR_NEUTRAL;  // spaces, punctuation, symbols
}

/*
 * Paired characters that have to be swapped inside a right-to-left run.
 *
 * A bracket is stored logically -- an opening one opens the phrase -- but drawn
 * positionally. Reversing a run moves the opening bracket to the right-hand
 * end, where an opening bracket is the wrong shape: "(text)" would come out as
 * ")text(" and look like a typo rather than like Persian.
 */
uint32_t mirrored(uint32_t cp) {
  switch (cp) {
    case '(': return ')';
    case ')': return '(';
    case '[': return ']';
    case ']': return '[';
    case '{': return '}';
    case '}': return '{';
    case '<': return '>';
    case '>': return '<';
    default: return cp;
  }
}

/// Decodes one UTF-8 sequence, advancing *p. Returns 0 at the end of the string.
/// Anything malformed is taken as a single Latin-1 byte, which is what the rest
/// of the firmware does with tags that are not valid UTF-8.
uint32_t utf8_next(const uint8_t **p) {
  const uint8_t *s = *p;
  const uint8_t c = s[0];
  if (c == 0) return 0;
  if (c < 0x80) {
    *p = s + 1;
    return c;
  }
  if ((c & 0xE0) == 0xC0 && (s[1] & 0xC0) == 0x80) {
    *p = s + 2;
    return ((uint32_t)(c & 0x1F) << 6) | (uint32_t)(s[1] & 0x3F);
  }
  if ((c & 0xF0) == 0xE0 && (s[1] & 0xC0) == 0x80 && (s[2] & 0xC0) == 0x80) {
    *p = s + 3;
    return ((uint32_t)(c & 0x0F) << 12) | ((uint32_t)(s[1] & 0x3F) << 6) |
           (uint32_t)(s[2] & 0x3F);
  }
  if ((c & 0xF8) == 0xF0 && (s[1] & 0xC0) == 0x80 && (s[2] & 0xC0) == 0x80 &&
      (s[3] & 0xC0) == 0x80) {
    *p = s + 4;
    return 0xFFFD;  // astral: no font here has these
  }
  *p = s + 1;
  return c;
}

/// Encodes one codepoint. Returns bytes written, or 0 if it would not fit --
/// which is what keeps truncation on a character boundary.
size_t utf8_put(char *dst, size_t cap, size_t at, uint32_t cp) {
  if (cp < 0x80) {
    if (at + 1 > cap) return 0;
    dst[at] = (char)cp;
    return 1;
  }
  if (cp < 0x800) {
    if (at + 2 > cap) return 0;
    dst[at] = (char)(0xC0 | (cp >> 6));
    dst[at + 1] = (char)(0x80 | (cp & 0x3F));
    return 2;
  }
  if (at + 3 > cap) return 0;
  dst[at] = (char)(0xE0 | (cp >> 12));
  dst[at + 1] = (char)(0x80 | ((cp >> 6) & 0x3F));
  dst[at + 2] = (char)(0x80 | (cp & 0x3F));
  return 3;
}

}  // namespace

bool text_has_arabic(const char *s) {
  if (s == nullptr) return false;
  const uint8_t *p = (const uint8_t *)s;
  for (;;) {
    const uint32_t cp = utf8_next(&p);
    if (cp == 0) return false;
    if (is_arabic_block(cp)) return true;
  }
}

char *text_arabic_visual(const char *src, char *dst, size_t cap) {
  if (dst == nullptr || cap == 0) return dst;
  dst[0] = 0;
  if (src == nullptr) return dst;

  // Nothing to do for a Latin string, which is the common case and should not
  // pay for any of what follows.
  if (!text_has_arabic(src)) {
    const size_t n = strlen(src);
    const size_t take = n < cap - 1 ? n : cap - 1;
    memcpy(dst, src, take);
    dst[take] = 0;
    return dst;
  }

  uint16_t cp[MAX_CP];
  uint8_t cls[MAX_CP];
  size_t n = 0;

  const uint8_t *p = (const uint8_t *)src;
  for (;;) {
    const uint32_t c = utf8_next(&p);
    if (c == 0 || n >= MAX_CP) break;
    // U+200C ZWNJ has done its job once shaping has read it, and U+200D ZWJ
    // likewise; both are recorded here and dropped at the end.
    if (c == 0xFFFD) continue;
    cp[n] = (uint16_t)c;
    cls[n] = joining_class(c);
    n++;
  }

  /*
   * Pass 1: lam + alef, before anything else.
   *
   * The ligature has to be resolved first because it changes what the letters
   * either side see as their neighbour: the pair becomes one unit, and the
   * letter after the alef must shape against the ligature rather than against
   * an alef that is no longer there. The alef's slot is blanked with 0 and
   * skipped from here on.
   */
  for (size_t i = 0; i + 1 < n; i++) {
    if (cp[i] != 0x0644) continue;  // lam
    // A transparent mark may sit between the two and does not break the pair.
    size_t j = i + 1;
    while (j < n && cls[j] == JOIN_TRANSPARENT) j++;
    if (j >= n) break;
    for (const auto &pair : LAM_ALEF) {
      if (cp[j] != pair[0]) continue;
      // Does anything before the lam join forward into it? If so the ligature
      // takes its final shape, otherwise its isolated one.
      size_t k = i;
      bool joins_prev = false;
      while (k > 0) {
        k--;
        if (cls[k] == JOIN_TRANSPARENT || cp[k] == 0) continue;
        joins_prev = (cls[k] == JOIN_DUAL || cls[k] == JOIN_CAUSING);
        break;
      }
      cp[i] = joins_prev ? pair[2] : pair[1];
      cls[i] = JOIN_RIGHT;  // the ligature ends in an alef, so it joins backwards
      cp[j] = 0;            // consumed
      cls[j] = JOIN_TRANSPARENT;
      break;
    }
  }

  /*
   * Pass 2: contextual shaping.
   *
   * "Joins to the previous letter" asks whether that letter can connect
   * *forward*, which only dual-joining and join-causing letters can do.
   * "Joins to the next" asks whether the next can connect *backward*, which
   * dual, right-joining and join-causing letters all can. Getting those two
   * asymmetric is what makes a word break after a dal and not after a beh.
   */
  for (size_t i = 0; i < n; i++) {
    if (cp[i] == 0 || cls[i] == JOIN_TRANSPARENT) continue;
    const ArabicForms *f = find_forms(cp[i]);
    if (f == nullptr) continue;  // no shapes: drawn as-is, which is correct
    if (cls[i] != JOIN_DUAL && cls[i] != JOIN_RIGHT) continue;

    bool joins_prev = false;
    for (size_t k = i; k > 0;) {
      k--;
      if (cp[k] == 0 || cls[k] == JOIN_TRANSPARENT) continue;
      joins_prev = (cls[k] == JOIN_DUAL || cls[k] == JOIN_CAUSING);
      break;
    }
    bool joins_next = false;
    for (size_t k = i + 1; k < n; k++) {
      if (cp[k] == 0 || cls[k] == JOIN_TRANSPARENT) continue;
      joins_next = (cls[k] == JOIN_DUAL || cls[k] == JOIN_RIGHT ||
                    cls[k] == JOIN_CAUSING);
      break;
    }
    // A right-joining letter has no forward-connecting shape to offer, however
    // willing its neighbour is.
    if (cls[i] == JOIN_RIGHT) joins_next = false;

    uint8_t want;
    if (joins_prev && joins_next) want = FORM_MEDIAL;
    else if (joins_prev) want = FORM_FINAL;
    else if (joins_next) want = FORM_INITIAL;
    else want = FORM_ISOLATED;
    // Fall back through the shapes the letter actually has rather than emitting
    // a zero, which would draw nothing at all.
    uint16_t glyph = f->form[want];
    if (glyph == 0 && want == FORM_MEDIAL) glyph = f->form[FORM_FINAL];
    if (glyph == 0 && want == FORM_INITIAL) glyph = f->form[FORM_ISOLATED];
    if (glyph == 0) glyph = f->form[FORM_ISOLATED];
    if (glyph != 0) cp[i] = glyph;
  }

  // Drop the consumed slots and the zero-width controls, so the reordering pass
  // below works on exactly what will be drawn.
  size_t m = 0;
  for (size_t i = 0; i < n; i++) {
    if (cp[i] == 0 || cp[i] == 0x200C || cp[i] == 0x200D) continue;
    cp[m] = cp[i];
    cls[m] = cls[i];
    m++;
  }
  n = m;

  /*
   * Pass 3: ordering.
   *
   * Two levels, resolved the simple way. Each character is strong left-to-right,
   * strong right-to-left, or neutral; neutrals take the direction of whatever
   * strong character precedes them, or the paragraph's own direction if none
   * does. The paragraph direction is that of its first strong character, which
   * is the rule that makes a Persian title lay out right to left and an English
   * one left to right without anybody having to say which is which.
   *
   * Then the line is emitted as runs: a right-to-left run has its characters
   * reversed, a left-to-right run does not, and when the paragraph is
   * right-to-left the runs themselves come out back to front. That is what
   * keeps "ESP32" readable inside a Persian title while the Persian around it
   * still reads from the right.
   */
  uint8_t dir[MAX_CP];
  uint8_t base = DIR_LTR;
  for (size_t i = 0; i < n; i++) {
    const uint8_t d = bidi_class(cp[i]);
    dir[i] = d;
    if (base == DIR_LTR && d == DIR_RTL) {
      bool earlier_ltr = false;
      for (size_t k = 0; k < i; k++) {
        if (dir[k] == DIR_LTR) { earlier_ltr = true; break; }
      }
      if (!earlier_ltr) base = DIR_RTL;
    }
  }
  uint8_t run = base;
  for (size_t i = 0; i < n; i++) {
    if (dir[i] == DIR_NEUTRAL) dir[i] = run;
    else run = dir[i];
  }

  size_t out = 0;
  if (base == DIR_RTL) {
    size_t end = n;
    while (end > 0) {
      size_t start = end;
      while (start > 0 && dir[start - 1] == dir[end - 1]) start--;
      if (dir[end - 1] == DIR_RTL) {
        for (size_t i = end; i > start; i--) {
          const size_t k = utf8_put(dst, cap - 1, out, mirrored(cp[i - 1]));
          if (k == 0) goto done;
          out += k;
        }
      } else {
        for (size_t i = start; i < end; i++) {
          const size_t k = utf8_put(dst, cap - 1, out, cp[i]);
          if (k == 0) goto done;
          out += k;
        }
      }
      end = start;
    }
  } else {
    size_t start = 0;
    while (start < n) {
      size_t end = start;
      while (end < n && dir[end] == dir[start]) end++;
      if (dir[start] == DIR_RTL) {
        for (size_t i = end; i > start; i--) {
          const size_t k = utf8_put(dst, cap - 1, out, mirrored(cp[i - 1]));
          if (k == 0) goto done;
          out += k;
        }
      } else {
        for (size_t i = start; i < end; i++) {
          const size_t k = utf8_put(dst, cap - 1, out, cp[i]);
          if (k == 0) goto done;
          out += k;
        }
      }
      start = end;
    }
  }

done:
  dst[out] = 0;
  return dst;
}
